[package]
name = "hwork3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
slug = "0.1.4"
serde = { version = "1.0", features = ["derive"] }
regex = "1"
